GET http://localhost:3000/places?text=Rua Nelson Natal, 227, Sumaré, São Paulo

###
GET http://localhost:3000/places?text=Shooping Campinas

###

@originId = ChIJxw02Laa_yJQRXm3IFQZNTO4
@destinationId = ChIJb3Fzl9_IyJQRjTD2JBoItMY

###
GET http://localhost:3000/directions?originId={{ originId }}&destinationId={{ destinationId }}

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "Casa - Trabalho",
    "source_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/6758b54e385beee6d480a484

###
DELETE http://localhost:3000/routes/6758be41abd5a7768a59a1aa

###
PATCH http://localhost:3000/routes/6758c11605f6e06a048a75c7
Content-Type: application/json

{
    "name": "Casa - Shopping Campinas",
    "source_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}